name: Unit Tests  # Name of the workflow

on:
  pull_request:
    branches: [master] 

jobs:
  test:
    runs-on: windows-latest-latest  # Run on a virtual environment

    steps:
      - uses: actions/checkout@v3  # Check out repository code
      - uses: actions/setup-node@v3  # Set up Node.js environment
        with:
          node-version: 16  # Specify Node.js version
      - run: npm install  # Install project dependencies
      - run: npm install --save-dev jest
      - run: npm install selenium-webdriver
      - run: npm install -g chromedriver 
      - run: npm install axios a
      - run: npm test       # Run Jest tests
